services:

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: jasko
      POSTGRES_DB: api
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    restart: unless-stopped
    build: .
    depends_on:
      - db
    environment:
      # Use nomes que o Spring Boot reconhece nativamente
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/api
      SPRING_DATASOURCE_USERNAME: jasko
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    networks:
      - default
      - proxy

volumes:
  pgdata:

networks:
  proxy:
    external: true